version: "3.7"
services:
  customers-service:
    build:
      context: .
      dockerfile: Dockerfile_ubuntuAsBaseImage
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped