# Use an official Maven image as the base image
FROM maven:3.9.9-amazoncorretto-21 AS build
# Set the working directory in the container
WORKDIR /app
# Copy the pom.xml and the project files to the container
COPY pom.xml .
COPY src ./src
# Build the application using Maven
RUN mvn clean package -DskipTests
FROM amazoncorretto:21
# Set the working directory in the container
WORKDIR /app
LABEL authors="Vikram"
COPY --from=build /app/target/*.jar customers_service.jar
ENTRYPOINT ["java","-jar","customers_service.jar"]
